name: CI

on:
  workflow_dispatch:
    inputs:
      build_linux:
        description: 'Build for Linux'
        required: false
        default: 'true'
        type: boolean
      build_macos:
        description: 'Build for macOS'
        required: false
        default: 'true'
        type: boolean

jobs:

  linux:
    name: Linux build
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build_linux == 'true' }}

    steps:
    - uses: actions/checkout@v5

    - name: Update
      run: sudo apt-get update

    - name: Dependencies
      run: sudo apt-get install build-essential cmake libboost-all-dev liblzma-dev

    - name: Configure
      run: cmake --version && cmake -B ${{github.workspace}}/build -Werror=dev -Werror=deprecated -DCONTINUOUS_INTEGRATION=1

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Check Style
      run: cmake --build ${{github.workspace}}/build --target style

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: innoextract-linux-binaries
        path: ${{github.workspace}}/build/innoextract

  macos:
    name: macOS build
    runs-on: macos-latest
    if: ${{ github.event.inputs.build_macos == 'true' }}

    steps:
    - uses: actions/checkout@v5

    - name: Update
      run: brew update

    - name: Workaround for Python install isssues - https://github.com/actions/runner-images/issues/8838
      run: brew install python@3 || brew link --overwrite python@3

    - name: Dependencies
      env:
        HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
      run: brew install boost xz

    - name: Configure
      run: cmake --version && cmake -B ${{github.workspace}}/build -Werror=dev -Werror=deprecated -DCONTINUOUS_INTEGRATION=1

    - name: Build
      run: cmake --build ${{github.workspace}}/build
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: innoextract-macos-binaries
        path: ${{github.workspace}}/build/innoextract
